//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TULbotpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Short { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDsuperior { get; set; }
        public string Website { get; set; }
        public string Adress { get; set; }
        public string Tel { get; set; }
        public string Maps { get; set; }
    }
}
