//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TULbotpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peoples
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Department { get; set; }
        public string Consultation { get; set; }
        public string Tel { get; set; }
    }
}
