//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TULbotpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QnA_table
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Keywords { get; set; }
        public string Answer { get; set; }
    }
}
